// generated by https://app.quicktype.io/

// To parse this JSON data, do
//
//     final appSettings = appSettingsFromJson(jsonString);

import 'dart:convert';

AppSettings appSettingsFromJson(String str) => AppSettings.fromJson(json.decode(str));

String appSettingsToJson(AppSettings data) => json.encode(data.toJson());

class AppSettings {
  AppSettings({
    required this.pistes,
    required this.refreshSettings,
  });

  List<Piste> pistes;
  RefreshSettings refreshSettings;

  factory AppSettings.fromJson(Map<String, dynamic> json) => AppSettings(
    pistes: List<Piste>.from(json["pistes"].map((x) => Piste.fromJson(x))),
    refreshSettings: RefreshSettings.fromJson(json["refreshSettings"]),
  );

  Map<String, dynamic> toJson() => {
    "pistes": List<dynamic>.from(pistes.map((x) => x.toJson())),
    "refreshSettings": refreshSettings.toJson(),
  };
}

class Piste {
  Piste({
    required this.name,
    required this.state,
    required this.notification,
  });

  String name;
  String state;
  bool notification;

  factory Piste.fromJson(Map<String, dynamic> json) => Piste(
    name: json["name"],
    state: json["state"],
    notification: json["notification"],
  );

  Map<String, dynamic> toJson() => {
    "name": name,
    "state": state,
    "notification": notification,
  };

}

class RefreshSettings {
  RefreshSettings({
    required this.interval,
    required this.last,
  });

  int interval;
  String last;

  factory RefreshSettings.fromJson(Map<String, dynamic> json) => RefreshSettings(
    interval: json["interval"],
    last: json["last"],
  );

  Map<String, dynamic> toJson() => {
    "interval": interval,
    "last": last,
  };
}
