// generated by https://app.quicktype.io/

// To parse this JSON data, do
//
//     final appSettings = appSettingsFromJson(jsonString);

import 'dart:convert';

AppSettings appSettingsFromJson(String str) => AppSettings.fromJson(json.decode(str));

String appSettingsToJson(AppSettings data) => json.encode(data.toJson());

class AppSettings {
  AppSettings({
    required this.pistes,
  });

  List<Piste> pistes;

  factory AppSettings.fromJson(Map<String, dynamic> json) => AppSettings(
    pistes: List<Piste>.from(json["pistes"].map((x) => Piste.fromJson(x))),
  );

  Map<String, dynamic> toJson() => {
    "pistes": List<dynamic>.from(pistes.map((x) => x.toJson())),
  };
}

class Piste {
  Piste({
    required this.name,
    required this.state,
    required this.notification,
  });

  String name;
  String state;
  bool notification;

  factory Piste.fromJson(Map<String, dynamic> json) => Piste(
    name: json["name"],
    state: json["state"],
    notification: json["notification"],
  );

  Map<String, dynamic> toJson() => {
    "name": name,
    "state": state,
    "notification": notification,
  };

}
