org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.daemon.enabled=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
org.gradle.workers.max=1
org.gradle.java.home=/nix/store/7q4av7wzjw098rcc83v1bb1blss1wccx-openjdk-21.0.12+2/lib/openjdk
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.enabled=false
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.experimental.privacysandbox.sdk.enable=false
android.defaults.buildfeatures.buildconfig=true
# Force Flutter to use the same Java
# flutter.java-home=/nix/store/7q4av7wzjw098rcc83v1bb1blss1wccx-openjdk-21.0.12+2/lib/openjdk
